config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  root 'hello#index'

  get 'about' => 'hello#about'
  

end

app/models/destination.rb
class Destination < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    if params[:country] == nil
      @destinations = Destination.all
    else
      @destinations = Destination.where(country: params[:country])
    end

    @my_countries = Destination.select(:country).order(:country).distinct



  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :populations, :avatar)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  	@homestate = 'California'
  	@countries = ["Mexico", "Canada", "Panama"]
  	@images = ["mexico1.jpg", "canada1.jpg", "panama1.jpg", "panama2.jpg"]

  	@image_hash = {"Mexico City" => "mexico1.jpg", "Canada" => "canada1.jpg", "Panama1" => "panama1.jpg", "Panama2" => "panama2.jpg"}
  end

  def about
  	@color = params[:color]
  	@size = params[:size].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :city, placeholder: "City", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :country, placeholder: "Country", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.number_field :populations, placeholder: "Population", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Describe the destination", class: "form-control", rows: "10" %>
  </div>
  <div class="form-group">
    <strong>Upload Image: </strong>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </p>
<% end %>

<h1>Listing Destinations</h1>

<ul class="nav nav-pills" role="tablist">
  <li><%= link_to "All", destinations_path %></li> 
  <% @my_countries.each do |c| %>
  <li><%= link_to c.country, destinations_path(country: c.country) %></li>
  <% end %>

</ul>
<%= link_to 'New Destination', new_destination_path, class: "btn btn-success" %>


<div class="row">
  <% @destinations.each do |destination| %>
    <div class="col-md-4">
      <div class="well index-wells"> 
      <% if destination.avatar.url == nil %>
        <%= image_tag "city_silhoutte.png", alt: "No Image found for destination", width: "250" %>
        <% else %>
        <p><%= image_tag destination.avatar.url, alt: "#{destination.city}", width: "250" %></p>
        <% end %>     
        <h2><%= "#{destination.city}, #{destination.country}" %></h2>
        <p><strong>Population</strong> <%= number_with_delimiter destination.populations %></p>
        <p><%= destination.description.html_safe %></p>
        <p><%= link_to 'Show', destination %>
        <p>  
        <%= link_to 'Edit', edit_destination_path(destination) %> <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      </div> 
    </div> 
  <% end %>
</div>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<% if notice != nil %>
  <p id="notice" class="alert alert-success" role="alert">
    <%= notice %>
  </p>
<% end %>
<p>
  <strong>City:</strong>
  <%= @destination.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @destination.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @destination.description %>
</p>

<p>
	<%= image_tag @destination.avatar.url, alt: "City Pic" %>
</p>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>

app/views/hello/about.html.erb
<style>
  body {
    background: <%= @color %>;
  }
</style>


<h1>About Me</h1>
<p>I'm a cool kid with lots of interesting things to say</p>

<p>My favorite color is <%= @color %></p>

<p>My shoe size is <%= @size %></p>
<% if @size > 12 %>
	My feet are <big>HUGE</big></p>
<% end %>

<p>
	<%= link_to "Red", about_path(color: "red", size: 12), class: "btn btn-danger" %>
</p>

<p>
	<%= link_to "Yellow", about_path(color: "yellow", size: 8), class: "btn btn-warning" %>
</p>

<p>
	<%= link_to "Green", about_path(color: "green", size: 14), class: "btn btn-success" %>
</p>

app/views/hello/index.html.erb
<h1>Welcome to My Travel Site</h1>
<p>This is my very first awesome travel site</p>
<p><%= @homestate %></p>

<ol>
<% @countries.each do |country| %>
	<li><%= country %></li>
<% end %>
</ol>

<%#= image_tag "mexico1.jpg", alt: "Mexico City", id: "mexico-pic", class: "travel-pics" %>
<%#= image_tag "canada1.jpg", alt: "Canada", id: "canada-pic", class: "travel-pics" %>
<%#= image_tag "panama1.jpg", alt: "Panama1", id: "panama-pic", class: "travel-pics" %>
<%#= image_tag "panama2.jpg", alt: "Panama2", id: "panama-pic", class: "travel-pics" %>

<!-- Passing Image Names through Array -->
<% @images.each do |image| %>
	<p><%= image_tag image, alt: "countries", class: "img-responsive" %></p>
<% end %>

<!-- Passing Image Names & Alts through Hash -->

<% @image_hash.each do |key, value| %>
	<p><%= image_tag value, alt: key, class: "img-responsive" %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Travel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Travel", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Destinations", destinations_path %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	<div class="container">
		<%= yield %>
	</div>
</body>
</html>